### ISSUE TITLE
can't run setupFabricNetwork.sh successfully by following errors

### ISSUE THREAD

**Issue by alexfhq** [ChainNova/trainingProjects#2]
when I run the "setupFabricNetwork.sh", there are following errors:
============== node modules installed already =============

module.js:549
    throw err;
    ^

Error: Cannot find module 'fabric-client'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/gopath/src/github.com/hyperledger/trainingProjects/billEndorse/config.js:3:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by sxl2020** [comment]
try
> npm install

in derectory billEndose to install the pakage

**Comment by leehommlee** [comment]
I have the same problem. How did you solve it？
