### ISSUE TITLE
can't run setupFabricNetwork.sh successfully by following errors

### ISSUE THREAD

**Issue by leehommlee** [ChainNova/trainingProjects#4]
when I run the "setupFabricNetwork.sh", there are following errors:
(The same error occurred when I ran the "fabric explorer",but I was not resolved. At that time, I changed the branch version that rely on node 8.11.x)
============== node modules installed already =============

/home/lh/trainingProjects/billEndorse/node_modules/fabric-client/lib/Client.js:742
	async _createOrUpdateChannel(request, have_envelope) {
	      ^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lh/trainingProjects/billEndorse/node_modules/fabric-client/index.js:25:18)
    at Module._compile (module.js:570:32)

So , How do you solve this problem? Thanks.

**Comment by BlueSky-YJS** [comment]
I have the same error!!!I use the nodejs version is v6.10.0,but the error is not reslove...how can i make it work???

**Comment by BlueSky-YJS** [comment]
anyone else can help resolve this problem ?
it is now I can't run this demo for study;howevery the environment follows the recommended configuration,so how can i do it...

**Comment by leehommlee** [comment]
hello,BlueSky,in my opinion, you can try other mature projects

**Comment by Yunhusheng** [comment]
We met the same issue, and it was solved by using latest version of Node.js and rebuild all the dependencies.
