### ISSUE TITLE
多机部署

### ISSUE THREAD

**Issue by LuffySmile** [ChainNova/trainingProjects#5]
这个如何实现多机部署啊？在单机上已经运行成功了，就是在多机部署的时候总是出错，不知道怎么部署。

**Comment by HKMing-star** [comment]
Excuse me, run ./setupFabricNetwork.sh with the following error, how is it solved:

=============node modules installed already =============

/home/alex/billEndorse/node_modules/fabric-client/lib/Client.js:684
	async _createOrUpdateChannel(request, have_envelope) {
	      ^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ming/billEndorse/node_modules/fabric-client/index.js:25:18)
    at Module._compile (module.js:570:32)

**Comment by LuffySmile** [comment]
you can try to use fabric-client V1.0 and node V6.10

**Comment by HKMing-star** [comment]
Thank you for your reply, but it doesn't work. Can you tell me your go、Docker、and Docker-Compose's version?

**Comment by LuffySmile** [comment]
go version go1.11 linux/amd64
Docker version 18.06.1-ce, build e68fc7a
docker-compose version 1.22.0, build f46880fe

**Comment by alvincaffrey** [comment]
> 这个如何实现多机部署啊？在单机上已经运行成功了，就是在多机部署的时候总是出错，不知道怎么部署。

[2021-01-12 00:43:43.143] [ERROR] Create-Channel - Error: 2 UNKNOWN: Stream removed
    at Object.exports.createStatusError (/home/alvin/go/trainingProjects/billEndorse/node_modules/grpc/src/common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (/home/alvin/go/trainingProjects/billEndorse/node_modules/grpc/src/client.js:233:26)
    at ClientDuplexStream._receiveStatus (/home/alvin/go/trainingProjects/billEndorse/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/home/alvin/go/trainingProjects/billEndorse/node_modules/grpc/src/client_interceptors.js:1311:15)
    at InterceptingListener._callNext (/home/alvin/go/trainingProjects/billEndorse/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/alvin/go/trainingProjects/billEndorse/node_modules/grpc/src/client_interceptors.js:618:8)
    at /home/alvin/go/trainingProjects/billEndorse/node_modules/grpc/src/client_interceptors.js:1127:18
/home/alvin/go/trainingProjects/billEndorse/app/create-channel.js:70
		throw new Error('Failed to initialize the channel: ' + err.stack ? err.stack : err);
		      ^

Error: Error: 2 UNKNOWN: Stream removed
    at Object.exports.createStatusError (/home/alvin/go/trainingProjects/billEndorse/node_modules/grpc/src/common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (/home/alvin/go/trainingProjects/billEndorse/node_modules/grpc/src/client.js:233:26)
    at ClientDuplexStream._receiveStatus (/home/alvin/go/trainingProjects/billEndorse/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/home/alvin/go/trainingProjects/billEndorse/node_modules/grpc/src/client_interceptors.js:1311:15)
    at InterceptingListener._callNext (/home/alvin/go/trainingProjects/billEndorse/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/alvin/go/trainingProjects/billEndorse/node_modules/grpc/src/client_interceptors.js:618:8)
    at /home/alvin/go/trainingProjects/billEndorse/node_modules/grpc/src/client_interceptors.js:1127:18
    at /home/alvin/go/trainingProjects/billEndorse/app/create-channel.js:70:9
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
请问这个错误如何解决呢
